import JSZip from 'jszip'
import type { GeneratedFile } from './generator/types'

export async function buildZip(gameName: string, files: GeneratedFile[], rojoJson: string): Promise<Blob> {
  const zip = new JSZip()
  const root = zip.folder(gameName.replace(/\s+/g, ''))!

  // Rojo project config
  root.file('default.project.json', rojoJson)

  // All generated Lua files
  for (const file of files) {
    root.file(file.path, file.content)
  }

  // README
  root.file('README.txt', buildReadme(gameName, files))

  return zip.generateAsync({ type: 'blob', compression: 'DEFLATE', compressionOptions: { level: 6 } })
}

function buildReadme(name: string, files: GeneratedFile[]): string {
  return `${name} — Generated by Roblox AI Generator
${'='.repeat(50)}

HOW TO USE:
1. Install Rojo v7: https://rojo.space
2. Run: rojo serve
3. Open Roblox Studio
4. Install the Rojo Studio plugin
5. Click Connect in the Rojo plugin panel

FILES GENERATED (${files.length} scripts):
${files.map(f => `  ${f.path} (${f.lines} lines)`).join('\n')}

ARCHITECTURE:
  Server entry:  ServerScriptService/GameManager.server.lua
  Client entry:  StarterPlayer/StarterPlayerScripts/PlayerController.client.lua
  Data layer:    ServerScriptService/DataManager.server.lua
  Constants:     ReplicatedStorage/GameConfig.lua
  Events:        ReplicatedStorage/RemoteEvents.lua

Generated ${new Date().toLocaleDateString()} by Roblox AI Generator
`
}
