plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\micha\\OneDrive\\Desktop\\code\\web-agency\\sites\\neat-barbershop"
publishOrigin = "default"
base = "C:\\Users\\micha\\OneDrive\\Desktop\\code\\web-agency\\sites\\neat-barbershop"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]